rewrite ^/forces/addcomments\.htm$ https://www.fec.gov/legal/search/rulemakings/?is_open_for_comment=true redirect;
rewrite ^/forces/?$ https://www.fec.gov/legal/search/rulemakings/?is_open_for_comment=true redirect;
rewrite ^/fosers/showpdf\.htm$ https://www.fec.gov/legal/search/rulemakings/documents/?doc_id=$arg_docid? redirect;
rewrite ^/fosers/?$ https://www.fec.gov/legal/search/rulemakings/ redirect;
rewrite ^/$ https://www.fec.gov/legal/search/rulemakings/ redirect;
