rewrite ^/forces/addcomments\.htm$ /legal/search/rulemakings/?is_open_for_comment=true redirect;
rewrite ^/forces/?$ /legal/search/rulemakings/?is_open_for_comment=true redirect;
rewrite ^/fosers/showpdf\.htm$ /legal/search/rulemakings/documents/?doc_id=$arg_docid redirect;
rewrite ^/fosers/?$ /legal/search/rulemakings/ redirect;
rewrite ^/$ /legal/search/rulemakings/ redirect;
