rewrite ^/eqsdocsMUR/([^/]+)\.pdf$ /legal/search/documents/?filename=$1 redirect;
rewrite ^/eqsdocsADR/([^/]+)\.pdf$ /legal/search/documents/?filename=$1 redirect;
rewrite ^/eqsdocsAF/([^/]+)\.pdf$ /legal/search/documents/?filename=$1 redirect;
rewrite ^/eqsdocs/([^/]+)\.pdf$ /legal/search/documents/?filename=$1 redirect;
rewrite ^/eqs/searcheqs /legal-resources/enforcement/ redirect;
rewrite ^/ /legal-resources/enforcement/ redirect;
